In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from simulator import Simulator

SyntaxError: invalid syntax (simulator.py, line 937)

In [3]:
# New settings - this turns out to be pretty impressive!!
# Think it beats the hand-designed controller!!
# Runs in about 3 minutes
sim = Simulator(autoInitialize=False, verbose=False)

sim.Sarsa_numInnerBins = 9
sim.Sarsa_numOuterBins = 9

sim.randomizeControl       = True
sim.percentObsDensity      = 15
sim.nonRandomWorld         = True
sim.circleRadius           = 1.0
sim.worldScale             = 0.5
sim.supervisedTrainingTime = 3000
sim.endTime                = 9000

sim.initialize()
sim.run()

initializing world object
Finished initialization
Simulation percentage complete: ( 10  # is complete)
# ---------
## --------
### -------
#### ------
##### -----
###### ----
####### ---
######## --
######### -
playButtonFPS 20.0
Total run time 182.012824059
Ticks (Hz) 988.935812249
Number of steps taken 179999
play
play
pause
play
play
play
pause
play


In [ ]:
# New settings - these end up in the car looping around and around
sim = Simulator(autoInitialize=False)

sim.randomizeControl       = True
sim.percentObsDensity      = 5
sim.nonRandomWorld         = True
sim.circleRadius           = 2.0
sim.worldScale             = 0.5
sim.supervisedTrainingTime = 1500
sim.endTime                = 4500

sim.initialize()
sim.run()

resetting eligibility traces to zero
building stick world
boundaries done
2500.0
10
initializing world object
building robot
buidling cell locator
starting a new single simulation
counter is  0
using QValue based controller =  False
resetting eligibility traces to zero
Had a collision, terminating simulation
starting a new single simulation
counter is  38
using QValue based controller =  False
resetting eligibility traces to zero
Had a collision, terminating simulation
starting a new single simulation
counter is  435
using QValue based controller =  False
resetting eligibility traces to zero
Had a collision, terminating simulation
starting a new single simulation
counter is  694
using QValue based controller =  False
resetting eligibility traces to zero
Had a collision, terminating simulation
starting a new single simulation
counter is  711
using QValue based controller =  False
resetting eligibility traces to zero
Had a collision, terminating simulation
starting a new single simulatio

IndexError: index 90000 is out of bounds for axis 0 with size 90000

play


IndexError: index 90000 is out of bounds for axis 0 with size 90000

In [ ]:
# Lucas' settings
sim = Simulator(autoInitialize=False)

sim.randomizeControl       = True
sim.percentObsDensity      = 2
sim.nonRandomWorld         = True
sim.circleRadius           = 3.0
sim.worldScale             = 0.5
sim.supervisedTrainingTime = 500
sim.endTime                = 1500

sim.initialize()
sim.run()

resetting eligibility traces to zero
building stick world
boundaries done
2500.0
10
initializing world object
building robot
buidling cell locator
starting a new single simulation
counter is  0
using QValue based controller =  False
resetting eligibility traces to zero
Had a collision, terminating simulation
starting a new single simulation
counter is  38
using QValue based controller =  False
resetting eligibility traces to zero
Had a collision, terminating simulation
starting a new single simulation
counter is  435
using QValue based controller =  False
resetting eligibility traces to zero
Had a collision, terminating simulation
starting a new single simulation
counter is  694
using QValue based controller =  False
resetting eligibility traces to zero
Had a collision, terminating simulation
starting a new single simulation
counter is  711
using QValue based controller =  False
resetting eligibility traces to zero
Had a collision, terminating simulation
starting a new single simulatio

In [3]:
# New settings
sim = Simulator(autoInitialize=False)

sim.randomizeControl       = True
sim.percentObsDensity      = 20
sim.nonRandomWorld         = True
sim.circleRadius           = 0.7
sim.worldScale             = 1.0
sim.supervisedTrainingTime = 500
sim.endTime                = 1500

sim.initialize()
sim.run()

resetting eligibility traces to zero
building stick world
boundaries done
10000.0
166
initializing world object
building robot
buidling cell locator
starting a new single simulation
counter is  0
using QValue based controller =  False
resetting eligibility traces to zero
Had a collision, terminating simulation
starting a new single simulation
counter is  19
using QValue based controller =  False
resetting eligibility traces to zero
Had a collision, terminating simulation
starting a new single simulation
counter is  327
using QValue based controller =  False
resetting eligibility traces to zero
Had a collision, terminating simulation
starting a new single simulation
counter is  437
using QValue based controller =  False
resetting eligibility traces to zero
Had a collision, terminating simulation
starting a new single simulation
counter is  799
using QValue based controller =  False
resetting eligibility traces to zero
Had a collision, terminating simulation
starting a new single simulat

IndexError: index 30000 is out of bounds for axis 0 with size 30000

reached end of tape, stopping playTime


In [5]:
from ddapp.consoleapp import ConsoleApp
c = ConsoleApp()
view = c.createView()
view.show()
c.start()

In [3]:
view.show()
c.start()

In [ ]:
import os
os.system("~/drakenew/drake-distro/build/bin/ddConsoleApp simulator.py")

In [75]:
from car import CarPlant
Car = CarPlant()
print Car.state
print Car.simulate()

[ 0.  0.  0.]
Finished simulation: [[  0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  7.99999864e-01   3.33300320e-04   1.24973249e-03]
 [  1.59999593e+00   2.66530357e-03   4.99580864e-03]
 [  2.39996955e+00   8.98971593e-03   1.12288801e-02]
 [  3.19987237e+00   2.12899518e-02   1.99333701e-02]
 [  3.99961205e+00   4.15335867e-02   3.10875278e-02]
 [  4.79903820e+00   7.16662207e-02   4.46634609e-02]
 [  5.59792964e+00   1.13604877e-01   6.06272373e-02]
 [  6.39598218e+00   1.69230564e-01   7.89389564e-02]
 [  7.19279776e+00   2.40380042e-01   9.95528482e-02]
 [  7.98787481e+00   3.28836735e-01   1.22417389e-01]
 [  8.78060031e+00   4.36320800e-01   1.47475428e-01]
 [  9.57024342e+00   5.64478265e-01   1.74664336e-01]
 [  1.03559513e+01   7.14869650e-01   2.03916152e-01]
 [  1.11367466e+01   8.88957749e-01   2.35157763e-01]
 [  1.19115276e+01   1.08809509e+00   2.68311082e-01]
 [  1.26790707e+01   1.31351109e+00   3.03293241e-01]
 [  1.34380346e+01   1.56629931e+00   3.4001680

In [49]:
print Car.simulateOneStep()

[  3.99999936e-01   1.66659443e-04   1.24973963e-03]


In [34]:
# Lolz, never use numpy arange

import numpy as np
dt = 0.05
for start in range(0,10):
    t = np.arange(start, start+dt*2.0, dt)
    print t

[ 0.    0.05]
[ 1.    1.05  1.1 ]
[ 2.    2.05  2.1 ]
[ 3.    3.05  3.1 ]
[ 4.    4.05]
[ 5.    5.05]
[ 6.    6.05]
[ 7.    7.05]
[ 8.    8.05]
[ 9.    9.05]


In [38]:
# Always use numpy linspace

import numpy as np
dt = 0.05
for start in range(0,10):
    t = np.linspace(start, start+dt, 2)
    print t



[ 0.    0.05]
[ 1.    1.05]
[ 2.    2.05]
[ 3.    3.05]
[ 4.    4.05]
[ 5.    5.05]
[ 6.    6.05]
[ 7.    7.05]
[ 8.    8.05]
[ 9.    9.05]


In [38]:
import numpy as np
a = np.random.randint(0, 3, size=(100,100))
np.count_nonzero(a)

6618

In [40]:
NW = (10, 10, 0)
something = (1, 1, 1)

print tuple(np.subtract(NW, something))

(9, 9, -1)


In [64]:
A = np.array(([0.1,1.0,2.0,3.0,4.0]))
print A
print 1.0/A

[ 0.1  1.   2.   3.   4. ]
[ 10.           1.           0.5          0.33333333   0.25      ]
